# Generated by Django 2.1.1 on 2018-09-06 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('FO', 'Food'), ('CL', 'Clothing'), ('EL', 'Electronics'), ('GR', 'Grocery'), ('TR', 'Tranportation'), ('HR', 'Housing'), ('ED', 'Education'), ('ET', 'Entertainment'), ('OT', 'Other')], default='OT', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
